[workspace]
#--------------------------------------------------------------------
authors = ["Kevin Wamae <wamaekevin@gmail.com>"]


#--------------------------------------------------------------------
# Repositories where pixi searches for packages, in order of priority
#--------------------------------------------------------------------
# - conda-forge: community-maintained, general-purpose packages. Should be listed first for R packages to avoid conflicts.
# - bioconda   : specialised bioinformatics tools and packages (SRA Toolkit, FastQC, samtools, etc.)
# - defaults   : anaconda’s official repository requires accepting additional terms of service for commercial use, so we exclude it
channels = ["conda-forge", "bioconda"]
name = "scrna-seq-analysis"


#--------------------------------------------------------------------
# Platforms to build for:
#--------------------------------------------------------------------
# - linux-64 for HPCs and local linux laptops
# - osx-64 for local development on MacOS
platforms = ["linux-64"]


#--------------------------------------------------------------------
# Version of the project
#--------------------------------------------------------------------
version = "0.1.0"


[tasks]
#--------------------------------------------------------------------
# Define tasks for the analysis
#--------------------------------------------------------------------
# use srun to create an interactive bash session
srun = "srun --ntasks=1 --cpus-per-task=4 --mem=16G --time=02:00:00 --pty bash"

#--------------------------------------------------------------------
# Part 1: Data download and quality control
#--------------------------------------------------------------------
# Covers downloading data from NCBI SRA and quality control for FASTQ files
[feature.part1-feature.dependencies]
sra-tools = "*"       # Download data from NCBI SRA
fastqc = "*"          # Quality control for FASTQ files
multiqc = "*"         # Aggregate QC reports
samtools = "*"        # Manipulate BAM files
wget = ">=1.25.0,<2"  # Download files from the web
python = ">=3.10"     # Python


#--------------------------------------------------------------------
# Part 2: QC and pre-processing
#--------------------------------------------------------------------
# Covers filtering empty droplets, detecting doublets, and removing low-quality cells
[feature.part2-feature.dependencies]
r-base = ">=4.3"               # Base R installation
r-seurat = ">=5.4.0,<6"        # Core scRNA-seq analysis
r-seuratobject = ">=5.3.0,<6"  # Seurat data structures
r-soupx = ">=1.6.2,<2"         # Ambient RNA correction

bioconductor-singlecellexperiment = ">=1.28.0,<2"  # Data structures for single-cell genomics
bioconductor-scdblfinder = ">=1.23.4,<2"           # Doublet detection
bioconductor-dropletutils = ">=1.26.0,<2"          # Droplet (empty) filtering toolkit

r-dplyr = ">=1.1.4,<2"        # Data manipulation
r-ggplot2 = "*"               # Core plotting
r-scales = "*"                # x/y axis scaling/formatting for ggplot2
r-languageserver = "*"        # Language server for R (needed for r-language-server)
r-jsonlite = "*"              # JSON parsing
r-httpgd = "*"                # HTTP Graphics Device for R
r-rlang = "*"                 # Grammar of Graphics for R


# #--------------------------------------------------------------------
# # Part 3: Integration & Clustering Packages
# #--------------------------------------------------------------------
# # Covers batch correction and integration of multiple samples
# [feature.part3-feature.dependencies]
# r-harmony = "*"                                    # Fast probabilistic integration
# bioconductor-batchelor = { channel = "bioconda" }  # FastMNN integration

# # Visualization packages
# r-ggplot2 = ">=4.0.3,<5"                           # Core plotting
# r-patchwork = ">=1.3.2,<2"                         # Combine multiple plots
# r-ggalluvial = ">=0.12.6,<0.13"                    # Sankey diagrams
# r-viridis = ">=0.6.5,<0.7"                         # Perceptually uniform colors
# r-rcolorbrewer = ">=1.1_3,<2"                      # Color palettes
# r-ggrepel = ">=0.9.8,<0.10"                        # Non-overlapping labels


# #--------------------------------------------------------------------
# # Part 4: Cell Type Annotation Packages
# #--------------------------------------------------------------------
# # Covers assigning biological identities to cell clusters
# [feature.part4-feature.dependencies]
# # Reference-based annotation
# bioconductor-singler = "*"      # Transfer labels from references
# bioconductor-celldex = "*"      # Reference cell type atlases

# # Marker-based annotation
# r-hgnchelper = ">=0.8.15,<0.9"  # Gene symbol validation
# r-openxlsx = ">=4.2.8.1,<5"     # Read Excel marker databases


[environments]
#--------------------------------------------------------------------
# Environments for different analysis stages
#--------------------------------------------------------------------
part1 = ["part1-feature"]
part2 = { features = ["part2-feature"], solve-group = "downstream" }
# part3 = { features = ["part3-feature"], solve-group = "downstream" }
# part4 = { features = ["part4-feature"], solve-group = "downstream" }
