# -----------------------------------------------------------------------------#
# STEP 3: Initial data exploration
# -----------------------------------------------------------------------------#

# --- 1. Basic Dimensions ---
# Tracks the starting size of the raw, unfiltered matrix.
cat("Total droplets:", ncol(seurat_obj), "\n")
cat("Total genes:", nrow(seurat_obj), "\n")


# --- 2. Matrix Sparsity Analysis ---
# WHAT IS SPARSITY?
# The percentage of slots in your expression matrix that are completely zero.
# A 99.9% sparsity means 999 out of 1000 slots contain no detected transcripts.
#
# WHY IS IT SO HIGH? (The defining hallmark of scRNA-seq)
# 1. Biological Reasons: A single cell only expresses a small fraction of the
#    genome at once. A T-cell has no use for bone or liver enzymes.
# 2. Technical Reasons ("Drop-out"): Miniscule starting material makes RNA
#    capture inefficient. Lowly expressed genes are frequently missed entirely
#    by the sequencing machine, creating false "drop-out" zeroes.
#
# WHY THIS STATISTIC MATTERS:
# - Expected: Standard datasets sit between 95.0% and 99.9% sparsity.
# - Low Sparsity (<95%): Warns you of major noise. Droplets might be flooded
#   with background ambient "soup" RNA, or contain large doublet cell clumps.
#
# COMPUTATIONAL NOTE:
# Standard data structures would crash your RAM trying to store millions of
# empty zeros. Seurat uses a "Sparse Matrix" (dgCMatrix) which only remembers
# the coordinates of non-zero entries, keeping computational overhead lean.

sparsity <- 1 - (
    sum(LayerData(seurat_obj, layer = "counts") > 0) /
        (nrow(seurat_obj) * ncol(seurat_obj))
)
cat("Matrix sparsity:", round(sparsity * 100, 1), "%\n")


# --- 3. Initial UMI Distributions ---
# Calculates the total raw transcripts (UMIs) captured per droplet.
umi_counts <- colSums(LayerData(seurat_obj, layer = "counts"))
cat("Median UMI per droplet:", median(umi_counts), "\n")

# RESOLVING THE "MEDIAN UMI = 1 or another tiny number" PARADOX:
# If you see a Median UMI of 1 (or another tiny number), do not panic! This is
# completely normal for an unfiltered RAW cell ranger matrix.
#
# The raw matrix contains millions of barcodes, but 99% of them are empty oil
# droplets trapping nothing but a tiny bit of cell-free background ambient soup
# (yielding 0, 1, or 2 total transcripts). Because these empty droplets heavily
# outnumber the real cells, they pull the overall dataset median down to near
# zero.
#
# THE BIPHASIC (BIMODAL) REALITY:
# If you were to plot this, you would see a sharp split into two populations:
#   - Group A (The Noise Pool): Millions of droplets hovering around 1 UMI.
#   - Group B (The Real Cells): A small handful of droplets with >1,000 UMIs.
#
# WE WILL START WITH A LOOSER CUTOFF OF >500 UMIs:
# Poking your head into the upper population by counting droplets with >500
# UMIs lets you bypass the sea of empty background noise to get an immediate,
# raw estimate of your true cellular yield.
#
# IMPORTANT: This >500 number is purely a manual sanity check! Do NOT use it
# as a hard filter yet. Step 4 (EmptyDrops) will use deep statistical profiling
# to save valid, low-RNA cells (like platelets) while dropping the background.

cat(
    "Droplets with >500 UMI:", sum(umi_counts > 500),
    "(likely cells, will be validated by EmptyDrops)\n"
)


# -----------------------------------------------------------------------------#
# SUMMARY & PIPELINE MILESTONE TRANSITION
# -----------------------------------------------------------------------------#
# WHERE WE STARTED:
# We loaded a raw matrix representing every single barcode generated by the 10x
# microfluidic chip. At that stage, we only knew the physical constraints of our
# input file: a giant, unvetted data block containing over a million barcodes.
#
# WHAT WE HAVE ACCOMPLISHED:
# In this step, we ran a diagnostic diagnostic audit. We uncovered a massive
# 99.9% global sparsity and a baseline median UMI of ~1. Rather than treating
# this as an experimental failure, our exploration demystified these values as
# the expected signature of an unfiltered raw dataset dominated by ambient noise.
# By checking for droplets with >500 UMIs, we proved that a viable, high-count
# population of real cells is hiding within the matrix.
#
# WHERE WE ARE HEADING (STEP 4):
# Right now, our dataset is still a mixture of a million empty soup droplets and
# a small population of true cells. If we were to apply a simple, rigid UMI
# cutoff here to get rid of the noise, we would accidentally kill off tiny,
# quiescent, low-RNA cells (like resting lymphocytes) that naturally live below
# that threshold.
#
# In Step 4, we will pass this raw matrix to EmptyDrops. Instead of looking at
# transcript volume alone, the algorithm will model the expression pattern of
# the ambient background soup and run a customized statistical test on every
# droplet, allowing us to dynamically rescue true, small cells while cleanly
# evacuating the empty background noise.
# -----------------------------------------------------------------------------#
