# ****************************************************************************#
# STEP 6: Doublet detection with scDblFinder
# ****************************************************************************#


# --- THE PROBLEM OF DOUBLETS ---
# ****************************************************************************#
#   A doublet occurs when two or more individual cells are accidentally wrapped
#   inside the exact same microfluidic oil droplet.
#
# WHY DOUBLETS DESTROY DOWNSTREAM ANALYSIS:
#   Because they share a single droplet barcode, their transcripts mix into a
#   single profile. This creates severe analytical issues:
#     1. False Hybrid States: A T-cell fused with a Macrophage will look like a
#        completely new, phantom "hybrid" cell type expressing both markers.
#     2. Count Inflation: They artificially inflate total cell counts.
#     3. Distorted Graphing: They confound lineage trajectory analyses and mess
#        up the mathematical calculation of differential expression.
#
# HOW scDblFinder DETECTS THEM (ARTIFICIAL CELL MODELING):
#   Instead of looking at simple count caps, `scDblFinder` mathematically
#   generates thousands of "synthetic doublets" in silico by randomly averaging
#   real cell profiles from your matrix. It then trains an advanced machine
#   learning model (xgboost) to find cells in your real dataset whose expression
#   signatures look suspiciously close to those artificial, blended doublets.


# --- WORKFLOW PREREQUISITE: JOIN LAYERS ---
# ****************************************************************************#
#   In Seurat v5+, data layers are often split by default. We must run
#   `JoinLayers` to consolidate the counts into a single continuous matrix so
#   that the underlying SingleCellExperiment structure can be mapped properly.
SEURAT_OBJ <- JoinLayers(SEURAT_OBJ)
SCE <- as.SingleCellExperiment(SEURAT_OBJ)


# --- RUN scDblFinder ---
# ****************************************************************************#
#   NOTE ON WARNINGS: `scDblFinder` frequently outputs warnings regarding empty
#   assay layers or deprecated xgboost parameters due to package version
#   changes. These are entirely harmless technical notifications. The core
#   algorithm only requires raw counts to function perfectly. We mask them
#   using `suppressWarnings`.
set.seed(100)

SCE <- LOG_STEP("Running scDblFinder doublet detection...", {
  suppressWarnings({
    scDblFinder(
      sce = SCE,
      dbr = NULL,
      verbose = FALSE,
      BPPARAM = BiocParallel::MulticoreParam(workers = N_WORKERS)
    )
  })
})


# --- EXTRACT RESULTS ---
# ****************************************************************************#
#   We retrieve the binary classification (Singlet vs Doublet) and the
#   continuous probability score generated by scDblFinder and map them into
#   our Seurat metadata.
SEURAT_OBJ$doublet_class <- ifelse(
  SCE$scDblFinder.class == "doublet",
  "Doublet",
  "Singlet"
)

# Store the continuous probability score generated by scDblFinder
SEURAT_OBJ$doublet_score <- SCE$scDblFinder.score


# --- BRIEF FEEDBACK & LOGGING ---
# ****************************************************************************#
# Count the number of identified doublets
N_DOUBLETS <- sum(SEURAT_OBJ$doublet_class == "Doublet")

# Calculate the doublet rate as a percentage
DOUBLET_RATE <- N_DOUBLETS / ncol(SEURAT_OBJ) * 100


# --- UNDERSTANDING EXPECTED DOUBLET RATES ---
# ****************************************************************************#
#   The number of doublets scales linearly with the density of your initial cell
#   suspension loading. As a general rule of thumb for 10x Genomics platforms:
#   - ~1,000 cells recovered  -> Expect ~0.8% doublet rate.
#   - ~5,000 cells recovered  -> Expect ~3.0% to 4.0% doublet rate.
#   - ~10,000 cells recovered -> Expect ~7.0% to 10.0% doublet rate.
#
# DATA INTERPRETATION GUIDELINES:
#   - Standard/Expected: Seeing a ~10% doublet rate when your sample contains
#     near ~10,000 cells is considered normal and completely acceptable.
#   - High Red Flag (>15% for small preps): Suggests technical loading over-
#     concentration (too many cells packed together), or indicates that the
#     detector is being overly sensitive on a highly homogenous cell population.

# Print the number of doublets and the doublet rate
cat("Doublets:", N_DOUBLETS, "(", round(DOUBLET_RATE, 1), "%)\n")

# Track cells before doublet removal for QC summary
CELLS_BEFORE_DOUBLET_REMOVAL <- ncol(SEURAT_OBJ)


# --- QUICK UMAP FOR VISUALIZATION ---
# ****************************************************************************#
# We normalize and generate rapid UMAP coordinates. The default method for
# RunUMAP is now natively set to 'uwot' using a cosine metric, meaning it
# runs entirely in R and no longer requires external Python configurations.

SEURAT_OBJ <- LOG_STEP("Generating UMAP for doublet visualization...", {
  SEURAT_OBJ %>%
    NormalizeData(verbose = FALSE) %>%
    FindVariableFeatures(nfeatures = 2000, verbose = FALSE) %>%
    ScaleData(verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE) %>%
    RunUMAP(dims = 1:30, verbose = FALSE) # Cleanly uses default native UWOT
})


# --- VISUAL PRE-FILTERING CHECK & RED FLAGS ---
# ****************************************************************************#
#  When you open "plots/02_doublets_umap.png", look specifically at the borders:
#   - Real Doublets: Typically cluster in narrow, tight intermediate "bridges"
#     or artificial islands suspended directly between two distinct major cell
#     type clusters.
#   - Homotypic Doublets: Doublets formed by two identical cell types (e.g.,
#     two T-cells) will sit embedded directly inside the main T-cell cluster
#     cloud. They are harder to visualize but are successfully flagged by the
#     math.
#
# CRITICAL FUTURE DIAGNOSTIC ALERTS (LOOK OUT FOR THESE):
#   - Red Flag A (Phantom Islands): A separate, isolated satellite cluster
#     made completely of red dots. Indicates an unremoved doublet population
#     mimicking a fake, novel cell type.
#   - Red Flag B (Over-Filtering): An entire genuine biological cluster
#     completely blanketed in red. Indicates a false positive where the math is
#     misidentifying highly active or large cells as doublets. Stop and lower
#     your `dbr` rate.
#   - Red Flag C (The Halo Effect): Red doublets forming a perfect outer ring
#     or "crust" around every singlet cluster. Indicates massive background
#     ambient RNA contamination that was not corrected properly in Step 5.

P3 <- DimPlot(
  SEURAT_OBJ,
  reduction = "umap",
  group.by = "doublet_class",
  cols = c("Singlet" = "#90E0EF", "Doublet" = "#EF233C"),
  pt.size = 1
) +
  labs(title = paste0("Doublet Detection (", round(DOUBLET_RATE, 1), "%)")) +
  theme(plot.title = element_text(face = "bold", size = 14))

ggsave(
  file.path(PLOTS_OUT_DIR, "02_doublets_umap.png"),
  plot = P3, width = 10, height = 6, dpi = 300
)


# --- EXCISE THE DOUBLETS ---
# ****************************************************************************#
# Once visually validated, we perform physical filtering to completely strip
# the flagged doublets from the dataset, retaining only verified singlets.
SEURAT_OBJ <- subset(SEURAT_OBJ, subset = doublet_class == "Singlet")

cat("After doublet removal:", ncol(SEURAT_OBJ), "cells\n")

# ****************************************************************************#
# SUMMARY & PIPELINE MILESTONE TRANSITION
# ****************************************************************************#
# WHERE WE STARTED:
# Before entering this step, we used SoupX (Step 5) to evaluate our dataset
# for ambient RNA leakage. Because our sample returned a clean baseline, we
# preserved our raw counts intact, entering this step with ~9,600 cell
# barcodes containing purified transcript expressions.
#
# WHAT WE HAVE ACCOMPLISHED:
# In this step, we addressed a physical hardware artifact: multi-cell droplets.
# We ran `scDblFinder` to construct in-silico synthetic doublets and trained a
# machine learning model to isolate real doublets from singlets. After injecting
# the classes via a combined `dplyr::mutate` approach, we generated a rapid
# PCA/UMAP pipeline using the modern, warning-free native R `uwot` engine to
# visually verify where the doublets clustered before permanently stripping
# them from our operational memory space.
#
# WHERE WE ARE HEADING (STEP 7):
# While our current dataset consists strictly of pure, singlet barcodes, we have
# not yet accounted for cell-level health. A droplet can contain a single,
# individual barcode, but that barcode might belong to a cell that ruptured,
# died, or stalled during tissue dissociation.
#
# In Step 7, we will transition to manual cell-level Quality Control (QC). We
# will calculate core diagnostic metrics like mitochondrial transcript
# percentages and ribosomal fractions. Instead of relying on blind mathematical
# thresholds, we will generate violin and scatter plots to manually locate the
# precise inflection points where healthy cells separate from dying fragments—
# drawing our final cell-filtering boundaries based entirely on data-driven
# visual inspection.
# ****************************************************************************#
